version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
